### ISSUE TITLE
Format strings hash not initialized with built-in formats

### ISSUE THREAD

**Issue by tlhackque** [runrig/spreadsheet-parseexcel#1]
First, thanks for merging all the fixes thru 0.64.  That's a lot of progress!

Now that date parsing doesn't blow up, I found another divot:

Per p. 279 of the MS spec, starting with BIFF8 there are built-in format strings that are not stored in the file.

These should be put into $workbook->{FormatStr} when the workbook is created.

Currently, I do:

```
my %formatStrings = ( %builtinFormats, %{ $workbook->{FormatStr} } );
```

in the application, but this shouldn't be necessary.  (%builtinFormats is defined below.)  It means every user has to research and add the strings for his/her locale.

GitHub won't let me attach a sample XLS file here.  But a reproducer is easy enough to create in Excel 2003:  put -11 in a cell, Ctrl/1 to format cells, select "Currency", and select the second '($1,234.10)' -- the one in Red.

This will create a cell with a format code of 37 (decimal), which is not stored in the file.  This means one can't call Utility::ExcelFmt().

I think the fix is in ParseExcel.pm, in parse, after calling Workbook->new
add
   $workbook->{FormatStr} = { %builtinFormats };

where %internalFormats is shown below.  (Cut and pasted from the spec - I noticed unbalanced parens around 0x29 - not sure if that's a typo in the spec or intentional.  The OpenOffice spec has the same text on p. 174.  In the OO spec, footnote refs aren't positioned as superscripts.)

Since 'General' amounts to 'Text', which requires no action, one could comment it out/omit it...

Of course, this is the US-English built-in table.  It would be nice to have a clean way for international users to specify their local format strings (codes < 164 are region-specific)  Maybe in the options to ParseExcel->new, a locale=> 'builtin_or_hash' arg?

Something like:

```
locale => 'us_english'  # For builtin builtins
or
locale => { currency => 'L/', formats => { 0x0e -> 'd/m/y', ...} )
```

That would let you distribute the builtins for US-English (base/default) and whatever others turn up.  The OO spec has limited info on Japanese & German.  But this scheme allows people to customize.)

It would also allow removing the code in the format parser that forces all currency symbols to '$".

```
my %builtinFormats = (
    0x00 => q{General},
    0x01 => q{0},
    0x02 => q{0.00},
    0x03 => q{#,##0},
    0x04 => q{#,##0.00},
    0x05 => q{($#,##0_);($#,##0)},
    0x06 => q{($#,##0_);[Red]($#,##0)},
    0x07 => q{($#,##0.00_);($#,##0.00)},
    0x08 => q{($#,##0.00_);[Red]($#,##0.00)},
    0x09 => q{0%},
    0x0a => q{0.00%},
    0x0b => q{0.00E+00},
    0x0c => q{# ?/?},
    0x0d => q{# ??/??},
    0x0e => q{m/d/yy},
    0x0f => q{d-mmm-yy},
    0x10 => q{d-mmm},
    0x11 => q{mmm-yy},
    0x12 => q{h:mm AM/PM},
    0x13 => q{h:mm:ss AM/PM},
    0x14 => q{h:mm},
    0x15 => q{h:mm:ss},
    0x16 => q{m/d/yy h:mm},
    0x25 => q{(#,##0_);(#,##0)},
    0x26 => q{(#,##0_);[Red](#,##0)},
    0x27 => q{(#,##0.00_);(#,##0.00)},
    0x28 => q{(#,##0.00_);[Red](#,##0.00)},
    0x29 => q{_(* #,##0_);_(* (#,##0);_(* "-"_);_(@_)},
    0x2a => q{_($* #,##0_);_($* (#,##0);_($* "-"_);_(@_)},
    0x2b => q{_(* #,##0.00_);_(* (#,##0.00);_(* "-"??_);_(@_)},
    0x2c => q{_($* #,##0.00_);_($* (#,##0.00);_($* "-"??_);_(@_)},
    0x2d => q{mm:ss},
    0x2e => q{[h]:mm:ss},
    0x2f => q{mm:ss.0},
    0x30 => q{##0.0E+0},
    0x31 => q{@},
);
```

By the way, if you want to document how to use the result of parsing format strings, here is the code I'm currently using; it shows how to deal with color codes:

```
 my $cellType = $cell->type() || 'Text';
 my $formatNo;
my %formatColors = (
    '[Black]'   => 1,
    '[White]'   => 2,
    '[Red]'     => 3,
    '[Green]'   => 4,
    '[Blue]'    => 5,
    '[Yellow]'  => 6,
    '[Magenta]' => 7,
    '[Cyan]'    => 8,
);

              if (
                    $cellType =~ /^(Numeric|Date)$/
                    && (   ( $formatNo = $format->{FmtIdx} )
                        && ( my $formatStr = $formatStrings{$formatNo} ) )
                  )
                {

                    # Formatted number or date
                    #0 is 'number_type', undoc & not used
                    #1 is 'want color, locale'
                    #
                    # Color numbers are 7 less than rgb_indices

                    my ( $dval, $color, $locale ) =
                      Spreadsheet::ParseExcel::Utility::ExcelFmt( $formatStr,
                        $cell->unformatted, $workbook->using_1904_date, 0, 1 );
                   if ( defined $color && $color ne '' ) {
                        my $idx;
                        $idx = $formatColors{$color} + 7
                          if ( exists $formatColors{$color} );
                        unless ( defined $idx ) {
                            if ( $color =~ /^\[Color(\d+)\]$/ ) {
                                $idx = $1 + 7;
                            }
                        }
                        if ( defined $idx ) {
                            $color = lc( $workbook->color_idx_to_rgb($idx) );
                             # $color is now a RGB hex code
                        }
                    } else { # Use default text color }
                   # $dval is the decoded value suitable for display
}
```

**Comment by runrig** [comment]
> put -11 in a cell, Ctrl/1 to format cells, select "Currency", and select the second '($1,234.10)' -- the one in Red.

I did that, and ended up with format 8, which had the proper format string.

> I think the fix is in ParseExcel.pm, in parse, after calling Workbook->new

That is where the FmtClass is set (FmtDefault by default), and that class contains all the builtin format string defaults that you mention. The docs suggest writing a different format class for anything that is not the default, and comes with a few alternatives (FmtJapan, etc), though it probably makes sense to make it easy to just drop in a different format string hash.

**Comment by tlhackque** [comment]
Not sure why I got another format number, but I did.

But I figured this out.   We don't need a SPE change after all.

Yes, the default classes are in the Formatter classes, which I missed.  
Sorry about that.  I was too focused on the app.

My issue is that I need the color from the format string, which 
overrides the color in the cell format.
Ideally, the code that populates the cell (it calls ExcelFmt) would just 
save the color (and locale) for consumers.  But it doesn't.

However, we can work-around this if we can call ExcelFmt with the 'want 
color & locale' argument true.  And I shouldn't have to create a custom 
Formatter to do that.

The hashes with the format strings in the Formatter classes aren't 
accessible - they are my variables.  But... FmtString() in the Formatter 
class will do what's necessary.

So this works in the application, and lets the formatter class provide 
the right format string:

if ($cellType =~ /^(Numeric|Date)$/
                     && $format->{FmtIdx} )  # This filters out 'General'
                 {

```
                 # Formatted number or date
                 # 1 is 'want color, locale'
                 #
                 # Color numbers are 7 less than rgb_indices
                 # [Color1] - [Color56] are defined.

                 my $formatStr =
                   $workbook->{FmtClass}->FmtString( $cell, $workbook );

                 my ( $dval, $color, $locale ) =
                   Spreadsheet::ParseExcel::Utility::ExcelFmt( 
```

$formatStr,
                         $cell->unformatted, $workbook->using_1904_date,
                         $cell->{Type}, 1 );

```
       if( defined $color && $color ne '' ) { # $color isn't always 
```

returned.
             my $idx;
             $idx = $formatColors{$color}  + 7
                  if( exists $formatColors{$color} );  # This maps 
[Black] to 1 .. [Cyan] to 8 as before.
             if  ( !defined $idx && $color =~ /^[Color(\d+)]$/ ) {  # 
Color numbers
                 $idx = $1 + 7;
             }
             if( defined $idx ) {
                  $color = lc ( $workbook->color_idx_to_rgb($idx) ) :
                 # And here we have the RGBcolor to apply.
             }
    }
}

The doc could use some clarification, but I'm on my way.  Hope this 
helps someone else.

Timothe Litt

## ACM Distinguished Engineer

This communication may not represent the ACM or my employer's views,
if any, on the matters discussed.
